# Generated by Django 3.1.6 on 2021-02-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
